config:
  credentials:
  - id: mycreds
    password_var: GIT_PASS
    type: username_password
    username_var: GIT_USER
  ojete_calor: []
  project_repos:
    github.com/EOSC-synergy/checkstyle:
      branch: master
      repo: https://github.com/EOSC-synergy/checkstyle
    github.com/EOSC-synergy/sqaaas-web:
      branch: dev-diana
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERSERVER: https://hub.docker.com/
sqa_criteria:
  qc_functional:
    repos:
      this_repo:
        tox:
          testenv:
          - bandit
          tox_file: /deepaas-testing/tox.ini
  qc_style:
    repos:
      github.com/EOSC-synergy/checkstyle:
        commands:
        - mvn -f ./maven-project/checkstyle-samples/pom.xml checkstyle:check
        container: maven-testing
      this_repo:
        commands:
        - whatevernosensecommand
        container: node
